# Generated by Django 4.1.5 on 2023-01-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojaapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='produtos'),
        ),
        migrations.AddField(
            model_name='produto',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='produtos'),
        ),
        migrations.AddField(
            model_name='produto',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='produtos'),
        ),
    ]
