# Generated by Django 4.1.5 on 2023-01-30 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojaapp', '0003_rename_image_produto_image1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
