# Generated by Django 4.1.5 on 2023-01-31 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojaapp', '0004_alter_carro_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='image1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='image4',
        ),
        migrations.AlterField(
            model_name='pedido_order',
            name='total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
